### ISSUE TITLE
Fails on numbers below 1k

### ISSUE THREAD

**Issue by FractalMachinist** [JCalmCrasher/number-js-formatter#1]

**Comment by JCalmCrasher** [comment]
Hi @FractalMachinist, what idea do you have in mind for numbers below 1,000?

**Comment by FractalMachinist** [comment]
I realize I was really unclear, my apologies. I'd imagined 999 -> "999", and 1000 -> "1k". Right now (in my admittedly brief tests), numbers below 1k throw an error. 

EDIT: The specific error:

friendlyFormat(999)
Uncaught TypeError: Cannot read property '0' of undefined
at friendlyFormat (/workspaces/cellarium/node_modules/number-js-formatter/dist/src/friendly-format.js:56:21)

**Comment by JCalmCrasher** [comment]
> I realize I was really unclear, my apologies. I'd imagined 999 -> "999", and 1000 -> "1k". Right now (in my admittedly brief tests), numbers below 1k throw an error. EDIT: The specific error: friendlyFormat(999) Uncaught TypeError: Cannot read property '0' of undefined at friendlyFormat (/workspaces/cellarium/node_modules/number-js-formatter/dist/src/friendly-format.js:56:21)

Not an issue, thanks for that.

You mind making a PR for it?

**Comment by FractalMachinist** [comment]
Sure, it'll be a few days.
